/**
 * Generate api/seeds/managers.sql from api/seeds/users.csv, with a freshly
 * generated passphrase per manager.
 *
 *   npm run seed:build      # writes the SQL, prints the passphrases once
 *   npm run seed:local      # apply to the local D1
 *   npm run seed:remote     # apply to the deployed D1
 *
 * The passphrases are printed to the terminal and never stored anywhere but the
 * hash, so capture them when you run this — the commissioner distributes them
 * out of band. Re-running rotates every password; it does NOT disturb picks or
 * chat, because user ids are derived from the username and stay stable.
 *
 * The CSV's email column is deliberately ignored. Those addresses are
 * placeholders (one is even misspelled, `@fantasy.leage`), and login is by
 * username — so the typo is harmless rather than a permanent gotcha.
 */

import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { generatePassphrase, hashPassword, passphraseBits } from '../src/lib/password';

const SEASON = 2026;
const COMMISSIONER_LAST_FIRST = 'talty:tom';
const SEEDS_DIR = join(import.meta.dirname, '..', 'seeds');
const CSV_PATH = join(SEEDS_DIR, 'users.csv');
const SQL_PATH = join(SEEDS_DIR, 'managers.sql');

interface CsvRow {
  firstName: string;
  lastName: string;
  displayName: string;
}

function parseCsv(text: string): CsvRow[] {
  const lines = text.trim().split(/\r?\n/);
  const header = lines.shift();
  if (!header) throw new Error(`${CSV_PATH} is empty`);

  const columns = header.split(',').map((c) => c.trim());
  const index = (name: string) => {
    const i = columns.indexOf(name);
    if (i === -1) throw new Error(`${CSV_PATH} is missing a "${name}" column`);
    return i;
  };
  const firstIdx = index('first_name');
  const lastIdx = index('last_name');
  const displayIdx = index('display_name');

  return lines.map((line) => {
    const cells = line.split(',');
    return {
      firstName: cells[firstIdx]!.trim(),
      lastName: cells[lastIdx]!.trim(),
      displayName: cells[displayIdx]!.trim(),
    };
  });
}

/**
 * First name when it's unique in the league, otherwise first.last — so most
 * managers get to type `tom` while the two Joshes get `josh.bozym` and
 * `josh.yagel`.
 */
function assignUsernames(rows: CsvRow[]): string[] {
  const firstNameCounts = new Map<string, number>();
  for (const row of rows) {
    const key = row.firstName.toLowerCase();
    firstNameCounts.set(key, (firstNameCounts.get(key) ?? 0) + 1);
  }

  return rows.map((row) => {
    const first = row.firstName.toLowerCase();
    return firstNameCounts.get(first) === 1 ? first : `${first}.${row.lastName.toLowerCase()}`;
  });
}

/** Spread avatar hues around the colour wheel so no two managers look alike. */
function assignHue(index: number, total: number): number {
  return Math.round((20 + (index * 360) / total) % 360);
}

function sqlString(value: string): string {
  return `'${value.replace(/'/g, "''")}'`;
}

const rows = parseCsv(readFileSync(CSV_PATH, 'utf8'));
const usernames = assignUsernames(rows);

const statements: string[] = [
  '-- Generated by `npm run seed:build`. Do not edit; do not commit (gitignored).',
  `-- Contains password hashes for ${rows.length} managers.`,
  '',
  '-- The league year. `is_current` is what resolveSeason() looks for.',
  `INSERT INTO seasons (year, draft_status, rounds, is_current) VALUES (${SEASON}, 'pending', 10, true)`,
  '  ON CONFLICT(year) DO UPDATE SET is_current = true;',
  '',
];

const issued: { username: string; displayName: string; passphrase: string }[] = [];

for (const [i, row] of rows.entries()) {
  const username = usernames[i]!;
  const passphrase = generatePassphrase();
  const hash = await hashPassword(passphrase);
  // Derived, not random, so re-running this script rotates passwords without
  // orphaning picks or chat messages that reference the user.
  const id = `usr_${username.replace(/\./g, '_')}`;
  const isCommissioner =
    `${row.lastName.toLowerCase()}:${row.firstName.toLowerCase()}` === COMMISSIONER_LAST_FIRST;

  statements.push(
    `INSERT INTO users (id, username, display_name, first_name, last_name, avatar_hue, is_commissioner, password_hash, created_at)`,
    `  VALUES (${sqlString(id)}, ${sqlString(username)}, ${sqlString(row.displayName)}, ` +
      `${sqlString(row.firstName)}, ${sqlString(row.lastName)}, ${assignHue(i, rows.length)}, ` +
      `${isCommissioner ? 'true' : 'false'}, ${sqlString(hash)}, unixepoch() * 1000)`,
    `  ON CONFLICT(username) DO UPDATE SET password_hash = excluded.password_hash,`,
    `    display_name = excluded.display_name, avatar_hue = excluded.avatar_hue,`,
    `    is_commissioner = excluded.is_commissioner;`,
    '',
  );

  issued.push({ username, displayName: row.displayName, passphrase });
}

statements.push(
  '-- A default draft order in CSV order, so the draft room is usable straight',
  '-- away. The commissioner replaces it with PUT /api/draft/order (which can',
  '-- randomize) before the draft opens.',
);
for (const [i, username] of usernames.entries()) {
  statements.push(
    `INSERT INTO draft_order (season_year, slot, user_id) VALUES (${SEASON}, ${i + 1}, ` +
      `${sqlString(`usr_${username.replace(/\./g, '_')}`)})`,
    '  ON CONFLICT(season_year, slot) DO UPDATE SET user_id = excluded.user_id;',
  );
}

mkdirSync(dirname(SQL_PATH), { recursive: true });
writeFileSync(SQL_PATH, `${statements.join('\n')}\n`, 'utf8');

const commissioner = rows.findIndex(
  (row) =>
    `${row.lastName.toLowerCase()}:${row.firstName.toLowerCase()}` === COMMISSIONER_LAST_FIRST,
);

console.log(`Wrote ${SQL_PATH}`);
console.log(`${rows.length} managers, season ${SEASON}.`);
if (commissioner === -1) {
  console.warn(
    `WARNING: no commissioner matched "${COMMISSIONER_LAST_FIRST}" — nobody can run the draft.`,
  );
}
console.log(`\nPassphrases (${passphraseBits()} bits each) — captured only here:\n`);

const width = Math.max(...issued.map((m) => m.username.length));
for (const manager of issued) {
  const flag = manager.username === 'tom' ? '  (commissioner)' : '';
  console.log(`  ${manager.username.padEnd(width)}  ${manager.passphrase}${flag}`);
}
console.log('\nApply with: npm run seed:local   (or seed:remote once deployed)');
